### ISSUE TITLE
Download folder location

### ISSUE THREAD

**Issue by VIS-Repo** [yuler/gh-download#1]
Hi,

I tried running the example scripts from the readme (gh dl cli/cli .github/) and I got a lot of messages in the cmd window showing the download was successful but I can't find the folder/files. Prior to running the command I had created a new folder called 'cli' and cd'd to that. I'm sure I'm missing something really simple but I've scanned my entire disk and can't find anything. Any suggestions?

**Comment by yuler** [comment]
@VIS-Repo Hi, 

I'm sorry, in the last version I introduced a bug when I added `-output` flag

The bug default `--output` will be download to the root folder `/`.

I release a new version 0.2.0 for fix this bug. 

Now, you can try upgrade the extension, and try it again.

**Comment by VIS-Repo** [comment]
Thank you :-)
