### ISSUE TITLE
Support github.com url directly

### ISSUE THREAD

**Issue by lakuapik** [yuler/gh-download#2]
@yuler thank you for this amazing extension!

I just wonder, do you plan to add support using github.com url directly? like this one:

```sh
$ gh download https://github.com/ContainerSSH/examples/tree/main/quick-start
```

<img width="1211" alt="image" src="https://user-images.githubusercontent.com/20186786/190084089-f49f1207-7442-4249-94ca-ecc7806d7454.png">

Then download it directly into current folder.

---
PS:
As there is no discussion page for this repo, so i just create an issue. 
Feel free to close this if you dont plan to do it. Thanks again, cheers 🍻.

**Comment by yuler** [comment]
I will try it later

But now you can use this command

```bash
gh download ContainerSSH/examples quick-start/
```

**Comment by yuler** [comment]
Hi @lakuapik 

I release a new version [v0.3.0](https://github.com/yuler/gh-download/releases/tag/v0.3.0) for support this feature

thanks your idea
